/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Attachment } from './models/attachment';
export type { AttachmentRequest } from './models/attachment-request';
export type { AttachmentResponse } from './models/attachment-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { ChatRoom } from './models/chat-room';
export type { ChatRoomRequest } from './models/chat-room-request';
export type { Comment } from './models/comment';
export type { CommentRequest } from './models/comment-request';
export type { CommentResponse } from './models/comment-response';
export type { FriendShip } from './models/friend-ship';
export type { FriendShipRequest } from './models/friend-ship-request';
export type { GrantedAuthority } from './models/granted-authority';
export type { LikeRequest } from './models/like-request';
export type { Likes } from './models/likes';
export type { Message } from './models/message';
export type { MessageRequest } from './models/message-request';
export type { PageResponseCommentResponse } from './models/page-response-comment-response';
export type { PageResponsePostResponse } from './models/page-response-post-response';
export type { Post } from './models/post';
export type { PostRequest } from './models/post-request';
export type { PostResponse } from './models/post-response';
export type { RegistrationRequest } from './models/registration-request';
export type { Role } from './models/role';
export type { User } from './models/user';
export type { UserRequest } from './models/user-request';
export type { UserResponse } from './models/user-response';
