/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AttachmentRequest } from './models/attachment-request';
export type { AttachmentResponse } from './models/attachment-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { ChatRoomRequest } from './models/chat-room-request';
export type { ChatRoomResponse } from './models/chat-room-response';
export type { CommentRequest } from './models/comment-request';
export type { CommentResponse } from './models/comment-response';
export type { FriendShipRequest } from './models/friend-ship-request';
export type { FriendShipResponse } from './models/friend-ship-response';
export type { LikeRequest } from './models/like-request';
export type { MessageRequest } from './models/message-request';
export type { MessageResponse } from './models/message-response';
export type { PageResponseCommentResponse } from './models/page-response-comment-response';
export type { PageResponseFriendShipResponse } from './models/page-response-friend-ship-response';
export type { PageResponsePostResponse } from './models/page-response-post-response';
export type { PostRequest } from './models/post-request';
export type { PostResponse } from './models/post-response';
export type { RegistrationRequest } from './models/registration-request';
export type { UserRequest } from './models/user-request';
export type { UserResponse } from './models/user-response';
