/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AttachmentResponse } from '../../models/attachment-response';

export interface GetAllAttachments$Params {
}

export function getAllAttachments(http: HttpClient, rootUrl: string, params?: GetAllAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AttachmentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllAttachments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AttachmentResponse>>;
    })
  );
}

getAllAttachments.PATH = '/attachments/';
