spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
  profiles:
    active: dev # to set the active profile to dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB # to set the maximum file size
      max-request-size: 50MB

stringdoc:
  default-produces-media-type: application/json # to set the default media type for the API

server:
  servlet: 
    context-path: /api/v1/ # to set the context path for the API endpoints