spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gamindie_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver # to set the driver class name for the datasource
  jpa:
    hibernate:
      ddl-auto: update # to update the schema
    show-sql: false # to show the SQL queries
    properties:
      hibernate:
        format-sql: true # to format the SQL queries
    database: postgresql # to set the database platform
    database-platform: org.hibernate.dialect.PostgreSQLDialect # to set the database dialect
  mail:
    host: localhost
    port: 1025
    username: maildev
    password: maildev
    properties:
      mail:
        smtp:
          trust: "*" # to trust all certificates
          auth: true # to authenticate with the server
          starttls:
            enable: true # to enable the use of the STARTTLS command (if supported by the server)
          connectiontimeout: 5000 # to set the connection timeout
          timeout: 3000 # to set the socket read timeout
          writetimeout: 5000 # to set the write timeout

application: # to set the application properties
  security: # to set the security properties
    jwt:
      secret-key: FgTXl5sdvwySO1bAvv/ePZkY/OHCuqc49O/+9u+8bCk=  # to set the secret key for the JWT (Base64 encoded) should be at least 256 bits long
      expiration: 604800000   # to set the expiration time for the JWT about 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/auth/activate-account # to set the activation URL for the frontend
  file:
    upload:
      images-path: ./uploads/images/ # to set the images path
      videos-path: ./uploads/videos/ # to set the videos path
      audios-path: ./uploads/audios/ # to set the audios path
      documents-path: ./uploads/documents/ # to set the documents path
      
server:
  port: 8088 # to set the server port