/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatRoom } from '../../models/chat-room';

export interface GetChatRoomById$Params {
  id: number;
}

export function getChatRoomById(http: HttpClient, rootUrl: string, params: GetChatRoomById$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatRoom>> {
  const rb = new RequestBuilder(rootUrl, getChatRoomById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatRoom>;
    })
  );
}

getChatRoomById.PATH = '/chatrooms/{id}';
