/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatRoomResponse } from '../../models/chat-room-response';

export interface GetChatRoomOwner$Params {
}

export function getChatRoomOwner(http: HttpClient, rootUrl: string, params?: GetChatRoomOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatRoomResponse>>> {
  const rb = new RequestBuilder(rootUrl, getChatRoomOwner.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChatRoomResponse>>;
    })
  );
}

getChatRoomOwner.PATH = '/chatrooms/owner';
