/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Message } from '../models/message';
import { Post } from '../models/post';
export interface Attachment {
  createdBy?: number;
  createdData?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  message?: Message;
  metadata?: string;
  name?: string;
  post?: Post;
  type?: string;
  url?: string;
}
