/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatRoomResponse {
  id?: number;
  isActive?: boolean;
  name?: string;
  user1Id?: number;
  user2Id?: number;
}
