/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatRoomRequest {
  isActive?: boolean;
  name?: string;
  user1Id: number;
  user2Id: number;
}
