/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentResponse {
  content?: string;
  createdBy?: number;
  createdData?: string;
  id?: number;
  parentId?: number;
  postId?: number;
}
