/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentResponse } from '../models/attachment-response';
export interface MessageResponse {
  attachments?: Array<AttachmentResponse>;
  chatRoomId?: number;
  content?: string;
  id?: number;
  ownerId?: number;
  sentAt?: string;
  status?: string;
}
