/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentResponse } from '../models/attachment-response';
import { Comment } from '../models/comment';
import { Likes } from '../models/likes';
export interface PostResponse {
  attachments?: Array<AttachmentResponse>;
  comments?: Array<Comment>;
  content?: string;
  createdData?: string;
  id?: number;
  lastModifiedDate?: string;
  likes?: Array<Likes>;
  ownerFullName?: string;
  ownerId?: number;
  ownerProfilePicture?: string;
  tags?: Array<string>;
}
