/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentResponse } from '../models/attachment-response';
export interface PostResponse {
  attachments?: Array<AttachmentResponse>;
  content?: string;
  createdData?: string;
  id?: number;
  lastModifiedDate?: string;
  ownerFullName?: string;
  ownerId?: number;
  ownerProfilePicture?: string;
  tags?: Array<string>;
}
