/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  bio?: string;
  email?: string;
  firstName?: string;
  id: number;
  lastName?: string;
  profilePrictureId?: number;
}
