/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  accountLocked?: boolean;
  bio?: string;
  createdDate?: string;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  id?: number;
  profilePicture?: string;
  savedPosts?: Array<string>;
  socialLinks?: string;
}
