/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentResponse {
  id?: number;
  name?: string;
  type?: string;
  url?: string;
}
