/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageRequest {
  attachmentIds?: Array<number>;
  chatRoomId?: number;
  content: string;
  id?: number;
}
