/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Attachment } from '../models/attachment';
import { Comment } from '../models/comment';
import { Likes } from '../models/likes';
import { User } from '../models/user';
export interface Post {
  attachments?: Array<Attachment>;
  comments?: Array<Comment>;
  content?: string;
  createdBy?: number;
  createdData?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  likes?: Array<Likes>;
  owner?: User;
  tags?: Array<string>;
}
