/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createLike } from '../fn/like/create-like';
import { CreateLike$Params } from '../fn/like/create-like';

@Injectable({ providedIn: 'root' })
export class LikeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createLike()` */
  static readonly CreateLikePath = '/likes/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createLike()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLike$Response(params: CreateLike$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return createLike(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createLike$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLike(params: CreateLike$Params, context?: HttpContext): Observable<number> {
    return this.createLike$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
