// /* tslint:disable */
// /* eslint-disable */
// /* Code generated by ng-openapi-gen DO NOT EDIT. */

// import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
// import { Observable } from 'rxjs';
// import { filter, map } from 'rxjs/operators';
// import { StrictHttpResponse } from '../../strict-http-response';
// import { RequestBuilder } from '../../request-builder';

// import { AttachmentRequest } from '../../models/attachment-request';

// export interface UploadAttachment$Params {
//   request: AttachmentRequest;
//   body?: {
//   'sourceFile': Blob;
//   }
// }

// export function uploadAttachment(http: HttpClient, rootUrl: string, params: UploadAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
//   const rb = new RequestBuilder(rootUrl, uploadAttachment.PATH, 'post');
//   if (params) {
    
//      // Create FormData
//      const formData = new FormData();
    
//      // Append the file
//      if (params.body?.sourceFile) {
//        formData.append('sourceFile', params.body.sourceFile);
//      }
     
//      // Append request parameters
//      if (params.request.name) {
//        formData.append('name', params.request.name);
//      }
//     if (params.request.type) {
//         formData.append('type', params.request.type);
//     }
//      if (params.request.metadata) {
//        formData.append('metadata', params.request.metadata);
//      }
 
//      // Set the body to the FormData
//      rb.body(formData);
//   }

//   return http.request(
//     rb.build({ responseType: 'json', accept: '*/*', context })
//   ).pipe(
//     filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
//     map((r: HttpResponse<any>) => {
//       return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
//     })
//   );
// }

// uploadAttachment.PATH = '/attachments/';
