/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getFriendFeed } from '../fn/user/get-friend-feed';
import { GetFriendFeed$Params } from '../fn/user/get-friend-feed';
import { Post } from '../models/post';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFriendFeed()` */
  static readonly GetFriendFeedPath = '/users/feed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFriendFeed()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFriendFeed$Response(params?: GetFriendFeed$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Post>>> {
    return getFriendFeed(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFriendFeed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFriendFeed(params?: GetFriendFeed$Params, context?: HttpContext): Observable<Array<Post>> {
    return this.getFriendFeed$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Post>>): Array<Post> => r.body)
    );
  }

}
