/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCommentResponse } from '../../models/page-response-comment-response';

export interface GetDirectReplies$Params {
  id: number;
  page?: number;
  size?: number;
}

export function getDirectReplies(http: HttpClient, rootUrl: string, params: GetDirectReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCommentResponse>> {
  const rb = new RequestBuilder(rootUrl, getDirectReplies.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCommentResponse>;
    })
  );
}

getDirectReplies.PATH = '/comments/{id}/replies';
