/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PostService } from './services/post.service';
export { MessageService } from './services/message.service';
export { LikeService } from './services/like.service';
export { FriendShipControllerService } from './services/friend-ship-controller.service';
export { CommentService } from './services/comment.service';
export { ChatRoomService } from './services/chat-room.service';
export { AuthenticationService } from './services/authentication.service';
export { AttachmentService } from './services/attachment.service';
export { UserService } from './services/user.service';
