/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FriendShip } from '../../models/friend-ship';

export interface GetFriends$Params {
}

export function getFriends(http: HttpClient, rootUrl: string, params?: GetFriends$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FriendShip>>> {
  const rb = new RequestBuilder(rootUrl, getFriends.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FriendShip>>;
    })
  );
}

getFriends.PATH = '/friendships/friends';
